export const browserCoreExamples = [
  "clawdbot browser status",
  "clawdbot browser start",
  "clawdbot browser stop",
  "clawdbot browser tabs",
  "clawdbot browser open https://example.com",
  "clawdbot browser focus abcd1234",
  "clawdbot browser close abcd1234",
  "clawdbot browser screenshot",
  "clawdbot browser screenshot --full-page",
  "clawdbot browser screenshot --ref 12",
  "clawdbot browser snapshot",
  "clawdbot browser snapshot --format aria --limit 200",
];

export const browserActionExamples = [
  "clawdbot browser navigate https://example.com",
  "clawdbot browser resize 1280 720",
  "clawdbot browser click 12 --double",
  'clawdbot browser type 23 "hello" --submit',
  "clawdbot browser press Enter",
  "clawdbot browser hover 44",
  "clawdbot browser drag 10 11",
  "clawdbot browser select 9 OptionA OptionB",
  "clawdbot browser upload /tmp/file.pdf",
  'clawdbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "clawdbot browser dialog --accept",
  'clawdbot browser wait --text "Done"',
  "clawdbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "clawdbot browser console --level error",
  "clawdbot browser pdf",
];
